### PR TITLE
Small improvement

### PR DESCRIPTION
**Pull request by FirelightFlagboy**
- Correct unused `Result` in test.
- Update dependencies.
- Make feature `bytes` depends on `bytes` crate.

### CODE REVIEW

**Comment by Stargateur** [comment]
bytes feature already depend on bytes crate. that how cargo work for optional dep

**Comment by jeromefroe** [comment]
Thanks @FirelightFlagboy!

**Comment by FirelightFlagboy** [comment]
@Stargateur do you have a link to the documentation that adding 

```toml
[features]
bytes = ["dep:bytes"]
```

Was only required to make the configuration explicit ?

I have read <https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies> but it don't list that implicit behavior with optional dependencies.

**Comment by Stargateur** [comment]
the doc link you give tell it:

> By default, this optional dependency implicitly defines a feature that looks like this:

But anyway that exactly the same thing and at least this new form of dep is more flexible so I think it was still a good thing to do. Thus this increase the MSRV to 1.60

**Comment by FirelightFlagboy** [comment]
I didn't understand it that way, but now that you said so that make sens :)

**Pull request merged**
